// <auto-generated />
namespace Assignment_NET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202203171614349_updateDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
