// <auto-generated />
namespace Assignment_NET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateCart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateCart));
        
        string IMigrationMetadata.Id
        {
            get { return "202203171438216_updateCart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
